"""update database

Revision ID: 446019c5ae5e
Revises: 9a512c9f47ad
Create Date: 2026-02-14 14:46:46.802583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '446019c5ae5e'
down_revision: Union[str, Sequence[str], None] = '9a512c9f47ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_enrollment', 'enrollments', ['user_id', 'course_id'])
    op.alter_column('users', 'role',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    op.drop_constraint('unique_enrollment', 'enrollments', type_='unique')
    # ### end Alembic commands ###
